// src/vue/App.vue
<template>
  <div class="card">
    <TheHeader
      :active-contact="activeContact"
      @back="onClickBack"
    />

    <section
      class="card-content p-0"
      style="min-height: 500px; overflow-y: hidden; overflow-x: hidden;"
    >
      <transition
        name="slide-fade-horizontal"
        mode="out-in"
      >
        <ContactList
          v-if="!activeContact.code"
          :messages="messages"
          @click="onClickContact"
        />

        <ConversationWrapper
          v-else
          :to="activeContact.code"
          :messages="messages"
        />
      </transition>
    </section>

    <footer
      v-if="activeContact.code"
      class="card-footer p-3"
    >
      <FormMessage :to="activeContact.code" />
    </footer>
  </div>
</template>

<script>
import storeMessages from '../store/messages';
import TheHeader from './components/TheHeader';
import ContactList from './components/ContactList';
const ConversationWrapper = () => import(/** webpackChunkName: component-vue-ConversationWrapper */ './components/ConversationWrapper');
const FormMessage = () => import(/** webpackChunkName: component-vue-FormMessage */ './components/FormMessage');

export default {
  components: {
    TheHeader,
    ContactList,
    ConversationWrapper,
    FormMessage,
  },
  data: () => ({
    activeContact: {},
    messages: [],
  }),
  created() {
    storeMessages.subscribe(this.onChangeMessages);
  },
  methods: {
    onClickContact(contact) {
      this.activeContact = contact;
    },
    onClickBack() {
      this.activeContact = {};
    },
    onChangeMessages() {
      this.messages = storeMessages.getState();
    },
  },
}
</script>

// src/svelte/App.svelte
<script>
import { fade } from 'svelte/transition';
import storeMessages from '../store/messages';
import TheHeader from './components/TheHeader.svelte';
import ContactList from './components/ContactList.svelte';
import FormMessage from './components/FormMessage.svelte';
import ConversationWrapper from './components/ConversationWrapper.svelte';

let activeContact = {};
let messages = [];

const onChangeMessages = () => {
  messages = storeMessages.getState();
};

const onClickBack = () => {
  activeContact = {};
};

const onClickContact = event => {
  activeContact = event.detail;
};

storeMessages.subscribe(onChangeMessages);
</script>

<div class="card">
  <TheHeader
    {activeContact}
    on:back={onClickBack}
  />

  <section
    class="card-content p-0"
    style="min-height: 500px; overflow: hidden;"
  >
    {#if !activeContact.code}
      <div in:fade={{ duration: 200 }}>
        <ContactList {messages} on:click={onClickContact} />
      </div>
    {:else}
      <div in:fade={{ duration: 200 }}>
        <ConversationWrapper to={activeContact.code} {messages} />
      </div>
    {/if}
  </section>

  {#if activeContact.code}
    <footer class="card-footer p-3">
      <FormMessage to={activeContact.code} />
    </footer>
  {/if}
</div>
