// src/svelte/components/FormMessage.svelte
<script>
import { CONTACT_CODE_SVELTE } from '../../helpers/contacts';
import { sendMessage } from '../../store/messages';

export let to = {};

let message = '';

const onSubmitForm = () => {
  if (!message) return;

  sendMessage({
    from: CONTACT_CODE_SVELTE,
    to,
    content: message,
  });

  message = '';
};
</script>

<form on:submit|preventDefault={onSubmitForm} class="is-flex-grow-1">
  <div class="field has-addons">
    <div class="control is-expanded">
      <input
        bind:value={message}
        placeholder="Put your message here.."
        class="input is-rounded"
        type="text"
        autofocus
      />
    </div>
    <div class="control">
      <button class="button is-danger is-rounded">
        <span class="icon is-small">
          <i class="fas fa-comment"></i>
        </span>
      </button>
    </div>
  </div>
</form>

// src/vue/components/FormMessage.vue
<template>
  <form class="is-flex-grow-1" @submit.prevent="onSubmit">
    <div class="field has-addons">
      <div class="control is-expanded">
        <input
          v-model.trim="message"
          placeholder="Put your message here.."
          class="input is-rounded"
          type="text"
          autofocus
        >
      </div>
      <div class="control">
        <button class="button is-primary is-rounded">
          <span class="icon is-small">
            <i class="fas fa-comment"></i>
          </span>
        </button>
      </div>
    </div>
  </form>
</template>

<script>
import { CONTACT_CODE_VUE } from '../../helpers/contacts';
import { sendMessage } from '../../store/messages';

export default {
  props: {
    to: {
      type: String,
      required: true,
    },
  },
  data: () => ({
    message: '',
  }),
  methods: {
    onSubmit() {
      if (!this.message) return;

      sendMessage({
        from: CONTACT_CODE_VUE,
        to: this.to,
        content: this.message,
      });

      this.message = '';
    },
  },
}
</script>
