// src/react/components/ContactList.jsx
import React from 'react';
import { getMyContacts, CONTACT_CODE_REACT } from '../../helpers/contacts';
import ContactListItem from './ContactListItem';

export default class ContactList extends React.Component {
  constructor(props) {
    super(props);
    this.contacts = getMyContacts(CONTACT_CODE_REACT);
  }

  render() {
    return (
      <div>
        {
          this.contacts.map(contact =>
            <ContactListItem
              key={contact.name}
              contact={contact}
              messages={this.props.messages}
              onClick={this.props.onClick}
            />
          )
        }
      </div>
    );
  }
}

// src/svelte/components/ContactList.svelte
<script>
import { createEventDispatcher } from 'svelte';
import { getMyContacts, CONTACT_CODE_SVELTE } from '../../helpers/contacts';
import ContactListItem from './ContactListItem';

export let messages = [];

const dispatch = createEventDispatcher();

const contacts = getMyContacts(CONTACT_CODE_SVELTE);
</script>

{#each contacts as contact}
  <ContactListItem
    {contact}
    {messages}
    on:click={() => dispatch('click', contact)}
  />
{/each}
