// src/react/components/ConversationWrapper.jsx
import React from 'react';
import { TransitionGroup, CSSTransition } from 'react-transition-group';
import { CONTACT_CODE_REACT } from '../../helpers/contacts';
import { scrollElementToBottom } from '../../helpers/element';
import { getContactConversations } from '../../helpers/messages';
import MessageBubble from './MessageBubble';

export default class ConversationWrapper extends React.Component {
  constructor(props) {
    super(props);

    this.refMessageContainer = React.createRef();
  }

  get conversations () {
    return getContactConversations(this.props.messages, CONTACT_CODE_REACT, this.props.to);
  }

  componentDidUpdate() {
    scrollElementToBottom(this.refMessageContainer.current);
  }

  render() {
    return (
      <div
        ref={this.refMessageContainer}
        className={`p-4 ${!this.conversations.length && 'is-flex is-align-items-center'}`}
        style={{
          height: 500,
          overflowY: 'auto'
        }}
      >
        {
          !this.conversations.length ?
            <div className="has-text-centered">
              <img src="/images/empty-chat-blue.png" />
              <p className="has-text-info">Start chatting with <span className="is-capitalized">{ this.props.to }</span></p>
            </div>
            :
            <TransitionGroup>
              {
                this.conversations.map(conversation =>
                  <CSSTransition
                    key={conversation.time}
                    timeout={0}
                    classNames="slide-fade"
                  >
                    <MessageBubble
                      isFromSelf={conversation.from === CONTACT_CODE_REACT}
                      title={conversation.from}
                      message={conversation.content}
                      time={conversation.time}
                    />
                  </CSSTransition>
                )
              }
            </TransitionGroup>
        }
      </div>
    );
  }
}

// src/svelte/components/ConversationWrapper.svelte
<script>
import { afterUpdate } from 'svelte';
import { fly } from 'svelte/transition';
import { CONTACT_CODE_SVELTE } from '../../helpers/contacts';
import { getContactConversations } from '../../helpers/messages';
import { scrollElementToBottom } from '../../helpers/element';
import MessageBubble from './MessageBubble';

export let to = '';
export let messages = [];

let messageContainer;

afterUpdate(() => {
  scrollElementToBottom(messageContainer);
});

$: conversations = getContactConversations(messages, CONTACT_CODE_SVELTE, to);
</script>

<div
  bind:this={messageContainer}
  class:is-flex={!conversations.length}
  class:is-align-items-center={!conversations.length}
  class="p-4"
  style="height: 500px; overflow-y: auto;"
>
  {#if !conversations.length}
    <div class="has-text-centered">
      <img src="/images/empty-chat-red.png" alt="Empty Chat" />
      <p class="has-text-danger">Start chatting with <span class="is-capitalized">{ to }</span></p>
    </div>
  {:else}
    {#each conversations as conversation}
      <div in:fly={{ duration: 200, y: 10 }}>
        <MessageBubble
          isFromSelf={conversation.from === CONTACT_CODE_SVELTE}
          title={conversation.from}
          message={conversation.content}
          time={conversation.time}
        />
      </div>
    {/each}
  {/if}
</div>
