// src/react/components/FormMessage.jsx
import React from 'react';
import { CONTACT_CODE_REACT } from '../../helpers/contacts';
import { sendMessage } from '../../store/messages';

export default class FormMessage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      message: '',
    };

    this.onChangeMessage = this.onChangeMessage.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }

  onChangeMessage(e) {
    this.setState({ message: e.target.value });
  }

  onSubmit(e) {
    e.preventDefault();

    if (!this.state.message) return;

    sendMessage({
      from: CONTACT_CODE_REACT,
      to: this.props.to,
      content: this.state.message,
    });

    this.setState({ message: '' });
  }

  render() {
    return (
      <form className="is-flex-grow-1" onSubmit={this.onSubmit}>
        <div className="field has-addons">
          <div className="control is-expanded">
            <input
              value={this.state.message}
              onChange={this.onChangeMessage}
              placeholder="Put your message here.."
              className="input is-rounded"
              type="text"
              autoFocus
            />
          </div>
          <div className="control">
            <button className="button is-info is-rounded">
              <span className="icon is-small">
                <i className="fas fa-comment"></i>
              </span>
            </button>
          </div>
        </div>
      </form>
    );
  }
}

// src/svelte/components/FormMessage.svelte
<script>
import { CONTACT_CODE_SVELTE } from '../../helpers/contacts';
import { sendMessage } from '../../store/messages';

export let to = {};

let message = '';

const onSubmitForm = () => {
  if (!message) return;

  sendMessage({
    from: CONTACT_CODE_SVELTE,
    to,
    content: message,
  });

  message = '';
};
</script>

<form on:submit|preventDefault={onSubmitForm} class="is-flex-grow-1">
  <div class="field has-addons">
    <div class="control is-expanded">
      <input
        bind:value={message}
        placeholder="Put your message here.."
        class="input is-rounded"
        type="text"
        autofocus
      />
    </div>
    <div class="control">
      <button class="button is-danger is-rounded">
        <span class="icon is-small">
          <i class="fas fa-comment"></i>
        </span>
      </button>
    </div>
  </div>
</form>
