// src/vue/components/MessageBubble.vue
<template>
  <div
    :class="{
      'level-right': isFromSelf,
    }"
  >
    <div
      :class="{
        'has-background-primary': isFromSelf,
      }"
      class="box is-inline-block p-2 mb-2"
      style="min-width: 100px; max-width: 300px;"
    >
      <div
        v-if="!isFromSelf"
        class="has-text-primary has-text-weight-bold is-capitalized"
      >
        {{ title }}
      </div>
      <div
        :class="{
          'has-text-white': isFromSelf,
        }"
        style="word-break: break-word;"
      >
        {{ message }}
      </div>
      <div
        :class="{
          'has-text-grey-light': !isFromSelf,
          'has-text-white-ter': isFromSelf,
        }"
        class="is-size-7"
      >
        {{ time | toShortTime }}
      </div>
    </div>
  </div>
</template>

<script>
import { toShortTime } from '../../helpers/date';

export default {
  filters:{
    toShortTime,
  },
  props: {
    isFromSelf: {
      type: Boolean,
      default: false,
    },
    title: {
      type: String,
      required: true,
    },
    message: {
      type: String,
      required: true,
    },
    time: {
      type: Number,
      required: true,
    },
  },
}
</script>

// src/svelte/components/MessageBubble.svelte
<script>
import { toShortTime } from '../../helpers/date';

export let isFromSelf = false;
export let title = '';
export let message = '';
export let time = null;
</script>

<div
  class:level-right={isFromSelf}
>
  <div
    class:has-background-danger={isFromSelf}
    class="box is-inline-block p-2 mb-2"
    style="min-width: 100px; max-width: 300px;"
  >
    {#if !isFromSelf}
      <div class="has-text-danger has-text-weight-bold is-capitalized">
        { title }
      </div>
    {/if}
    <div
      class:has-text-white={isFromSelf}
      style="word-break: break-word;"
    >
      { message }
    </div>
    <div
      class:has-text-grey-light={!isFromSelf}
      class:has-text-white-ter={isFromSelf}
      class="is-size-7"
    >
      { toShortTime(time) }
    </div>
  </div>
</div>
