// src/vue/components/ContactList.vue
<template>
  <div>
    <ContactListItem
      v-for="contact in contacts"
      :key="contact.name"
      :contact="contact"
      :messages="messages"
      @click.native="onClickContact(contact)"
    />
  </div>
</template>

<script>
import { getMyContacts, CONTACT_CODE_VUE } from '../../helpers/contacts';
import ContactListItem from './ContactListItem';

export default {
  components: {
    ContactListItem,
  },
  props: {
    messages: {
      type: Array,
      required: true,
    },
  },
  data: () => ({
    contacts: getMyContacts(CONTACT_CODE_VUE),
  }),
  methods: {
    onClickContact(contact) {
      this.$emit('click', contact);
    },
  },
}
</script>

// src/react/components/ContactList.jsx
import React from 'react';
import { getMyContacts, CONTACT_CODE_REACT } from '../../helpers/contacts';
import ContactListItem from './ContactListItem';

export default class ContactList extends React.Component {
  constructor(props) {
    super(props);
    this.contacts = getMyContacts(CONTACT_CODE_REACT);
  }

  render() {
    return (
      <div>
        {
          this.contacts.map(contact =>
            <ContactListItem
              key={contact.name}
              contact={contact}
              messages={this.props.messages}
              onClick={this.props.onClick}
            />
          )
        }
      </div>
    );
  }
}
