// src/svelte/components/MessageBubble.svelte
<script>
import { toShortTime } from '../../helpers/date';

export let isFromSelf = false;
export let title = '';
export let message = '';
export let time = null;
</script>

<div
  class:level-right={isFromSelf}
>
  <div
    class:has-background-danger={isFromSelf}
    class="box is-inline-block p-2 mb-2"
    style="min-width: 100px; max-width: 300px;"
  >
    {#if !isFromSelf}
      <div class="has-text-danger has-text-weight-bold is-capitalized">
        { title }
      </div>
    {/if}
    <div
      class:has-text-white={isFromSelf}
      style="word-break: break-word;"
    >
      { message }
    </div>
    <div
      class:has-text-grey-light={!isFromSelf}
      class:has-text-white-ter={isFromSelf}
      class="is-size-7"
    >
      { toShortTime(time) }
    </div>
  </div>
</div>

// src/react/components/MessageBubble.jsx
import React from 'react';
import { toShortTime } from '../../helpers/date';

export default class MessageBubble extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div
        className={this.props.isFromSelf ? 'level-right' : ''}
      >
        <div
          className={`box is-inline-block p-2 mb-2 ${this.props.isFromSelf ? 'has-background-info' : ''}`}
          style={{
            minWidth: 100,
            maxWidth: 300,
          }}
        >
          {
            !this.props.isFromSelf &&
            <div className="has-text-link has-text-weight-bold is-capitalized">
              { this.props.title }
            </div>
          }
          <div
            className={this.props.isFromSelf ? 'has-text-white' : ''}
            style={{
              wordBreak: 'break-word',
            }}
          >
            { this.props.message }
          </div>
          <div
            className={`is-size-7 ${!this.props.isFromSelf ? 'has-text-grey-light' : ''} ${this.props.isFromSelf ? 'has-text-white-ter' : ''}`}
          >
            { toShortTime(this.props.time) }
          </div>
        </div>
      </div>
    );
  }
}
