// src/vue/App.vue
<template>
  <div class="card">
    <TheHeader />

    <section class="card-content p-0" style="min-height: 500px;">
      <button
        v-for="contact in contacts"
        :key="contact.name"
        class="button button-chat is-fullwidth py-5"
        @click.prevent="onClickContact(contact)"
      >
        {{ contact.name }} ({{ messages.filter(message => message.from === contact.code && message.to === 'vue').length }})
      </button>
    </section>

    <footer v-if="activeContact" class="card-footer p-3">
      <FormMessage :to="activeContact" />
    </footer>
  </div>
</template>

<script>
import TheHeader from './components/TheHeader';
import FormMessage from './components/FormMessage';
import storeMessages from '../store/messages';

export default {
  components: {
    TheHeader,
    FormMessage,
  },
  data: () => ({
    activeContact: '',
    messages: [],
    contacts: [
      {
        name: 'React',
        code: 'react',
      },
      {
        name: 'Svelte',
        code: 'svelte',
      },
    ],
  }),
  created() {
    storeMessages.subscribe(this.onChangeMessages);
  },
  methods: {
    onClickContact(contact) {
      this.activeContact = contact.code;
    },
    onChangeMessages() {
      this.messages = storeMessages.getState();
    },
  },
}
</script>

<style scoped>
.button-chat {
  border-top: 0;
  border-left: 0;
  border-right: 0;
}
</style>

// src/react/App.jsx
import React from 'react';
import TheHeader from './components/TheHeader';
import FormMessage from './components/FormMessage';
import storeMessages from '../store/messages';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      activeContact: '',
      messages: [],
    };
    this.contacts = [
      {
        name: 'Vue',
        code: 'vue',
      },
      {
        name: 'Svelte',
        code: 'svelte',
      },
    ];

    this.onClickContact = this.onClickContact.bind(this);
    this.onChangeMessages = this.onChangeMessages.bind(this);

    storeMessages.subscribe(this.onChangeMessages);
  }

  onClickContact(e, contact) {
    e.preventDefault();
    this.setState({ activeContact: contact.code });
  }

  onChangeMessages() {
    this.setState({ messages: storeMessages.getState()});
  }

  render() {
    return (
      <div className="card">
        <TheHeader />

        <section className="card-content p-0" style={{ minHeight: 500 }}>
          {
            this.contacts.map(contact =>
              <button
                key={contact.code}
                className="button button-chat is-fullwidth py-5"
                onClick={e => this.onClickContact(e, contact)}
              >
                {contact.name} ({this.state.messages.filter(message => message.from === contact.code && message.to === 'react').length})
              </button>
            )
          }
        </section>

        {
          this.state.activeContact &&
          <footer className="card-footer p-3">
            <FormMessage to={this.state.activeContact} />
          </footer>
        }
      </div>
    );
  }
}
